---
- name: Check if awscli exists
  stat:
    path: /usr/local/bin/aws
  register: awscli_dir

- name: Download awscli zip
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /var/tmp/awscliv2.zip
  when: not awscli_dir.stat.exists

- name: Unzip awscli zip
  unarchive:
    src: /var/tmp/awscliv2.zip
    dest: /var/tmp/
    remote_src: yes
    creates: /var/tmp/awscli/
  when: not awscli_dir.stat.exists

- name: Run awscli install script
  command: ./aws/install
  args:
    chdir: /var/tmp
    creates: /usr/local/bin/aws
  become: true
  when: not awscli_dir.stat.exists

- name: Cleanup
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/var/tmp/awscli.zip"
    - "/var/tmp/awscli"